### ISSUE TITLE
TODO: minimod

### ISSUE THREAD

**Issue by amichuda** [minimod-nutrition/minimod-opt#5]
Before reading Justin code:

- [x] test against GAMS code to check for consistency (with with some caveats).
- [x] get rid of vasoilold from data
- [x] include relevant constraints
- [x] explore plotting functions
- [x] think about improving report function

After reading Justin's code:

- [x] incorporate constraints from larger model
- [x] explore sensitivity analysis 
- [x] explore the Monte Carlo simulations 

TODO:

- [x] create excel spreadsheet output
- [x] make adding constraints easier more elegant
   - [x] maybe output what constraint looks like?
- [x] create BAU comparison graphs
    - [x] this will include the minimum constraint argument
- [ ] refactor summary grouping functions 
- [x] refactor model creation as its own class
     - [x] This will help with the fact that model.clear() is weird and buggy
     - [x] If we create the base model when instantiation of `Minimod` occurs, we can stop multiple calls to `fit` from creating too many constraints.
- [x] refactor BAU constraint as its own class
- [x] make comparison map use bau class

Plotting TODO:

- [x] refactor plotting code
    - create abstract plotting class that takes care of formatting, titles, stuff like that
    - what to do about titles?
    - how to deal with so many arguments in mapping function
    - is there some way to streamline it?
    - create more attributes?
- [ ] allow bokeh plotting for daahboarding
- [x] make grouped bar plot of benefits over space for every intervention
- [x] make hydrograph of every run of montecarlo with reference average kind
- [x] make benchmark map
    - [x] give same vmin and vmax to share colors
    - [x] hide one legend so that they share one
- [x] change title for coverage ( or just add title argument). 
- [ ] no scientific notation
- [x] make intervention plot stacked
- [ ] change map colormap
- [x] make colormap the same for multiple maps 
     - [x] Multiple maps is probably going to be deprecated in
